"""initial schema

Revision ID: 94b3fb6a5f77
Revises: 
Create Date: 2026-07-22 17:25:47.749170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b3fb6a5f77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_repo'), ['repo'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_token_secret_hash'), ['secret_hash'], unique=True)

    op.create_table('lease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('run_attempt', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=255), nullable=False),
    sa.Column('pr', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'run_id', 'run_attempt', 'job', name='uq_lease_slot')
    )
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_pr'), ['pr'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_repo'), ['repo'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_secret_hash'), ['secret_hash'], unique=True)

    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('series', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('rep', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('deterministic', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=False),
    sa.Column('context', sa.String(length=16), nullable=False),
    sa.Column('trust', sa.String(length=16), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('base_sha', sa.String(length=40), nullable=True),
    sa.Column('merge_sha', sa.String(length=40), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('pr', sa.Integer(), nullable=True),
    sa.Column('workflow', sa.String(length=255), nullable=True),
    sa.Column('job', sa.String(length=255), nullable=True),
    sa.Column('runner', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('run_attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'run_attempt', 'job', 'series', 'rep', 'head_sha', 'position', 'group', name='uq_measurement_dedup')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_context'), ['context'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_head_sha'), ['head_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_pr'), ['pr'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_repo'), ['repo'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_series'), ['series'], unique=False)
        batch_op.create_index('ix_series_history', ['series', 'context', 'created_at'], unique=False)

    op.create_table('rate_bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_bucket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_bucket_key'), ['key'], unique=True)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('pr', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'pr', name='uq_report_pr')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_pr'), ['pr'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_repo'), ['repo'], unique=False)

    op.create_table('comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('head_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('delta_pct', sa.Float(), nullable=True),
    sa.Column('threshold_pct', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('n_baseline', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparison', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparison_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comparison', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparison_report_id'))

    op.drop_table('comparison')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_repo'))
        batch_op.drop_index(batch_op.f('ix_report_pr'))

    op.drop_table('report')
    with op.batch_alter_table('rate_bucket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_bucket_key'))

    op.drop_table('rate_bucket')
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index('ix_series_history')
        batch_op.drop_index(batch_op.f('ix_measurement_series'))
        batch_op.drop_index(batch_op.f('ix_measurement_role'))
        batch_op.drop_index(batch_op.f('ix_measurement_repo'))
        batch_op.drop_index(batch_op.f('ix_measurement_pr'))
        batch_op.drop_index(batch_op.f('ix_measurement_head_sha'))
        batch_op.drop_index(batch_op.f('ix_measurement_created_at'))
        batch_op.drop_index(batch_op.f('ix_measurement_context'))

    op.drop_table('measurement')
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_secret_hash'))
        batch_op.drop_index(batch_op.f('ix_lease_repo'))
        batch_op.drop_index(batch_op.f('ix_lease_pr'))

    op.drop_table('lease')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_secret_hash'))
        batch_op.drop_index(batch_op.f('ix_api_token_repo'))

    op.drop_table('api_token')
    # ### end Alembic commands ###
